dataset:
  args:
    cache_transformed: true
    reload_data: true
    skip_features:
      - flowrate_scaled
  pre_transforms:
    - args:
        remove_original: true
      type: HazenWilliamsWeights
  subsets:
    - args:
        root: saved/simulations/wntr/l-town/1_l-town_eps
      type: WDSGNNDataset
  transforms:
    - args:
        columns:
          - flowrate
      type: OrderEdges
    - args:
        extend_dimensions: true
        fully_connected: false
      type: VirtualSink
    - args:
        extend_dimensions: true
        fully_connected: false
      type: VirtualReservoirConnections
    - type: ToComplexData
    - args: { }
      type: MaskJunctionValues
debug: false
device: cuda:0
inspect: false
loader:
  args:
    batch_size: 1
    num_workers: 0
    shuffle: false
    test_split: 0.0
    validation_split: 0.0
  type: BaseGNNDataLoader
n_gpu: 1
name: SimplicialNet
seed: 90342

