experiment_name: 1_l-town_eps
fixed_params:
  network: L-TOWN_Real.inp
  options:
    hydraulic:
      demand_model: PDD
  seed: 90342
name_suffix: eps
number_of_runs: 1
result_processor:
  filter:
    filter_parallel_edges: null
  input_variables:
    link:
      properties:
      - initial_status
      - link_type
      - start_node_name
      - end_node_name
      - roughness
      - length
      - diameter
      signals:
      - flowrate
    node:
      properties:
      - node_type
      - elevation
      signals:
      - demand
      - head
  post_transforms:
  - node_names_to_ids
  target_variables:
    node:
      signals:
      - head
